# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arithmatica_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
import cv2
import tempfile
from PIL import Image, ImageOps
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QGraphicsScene, QSlider, QDialog, QVBoxLayout, QHBoxLayout, QSpinBox, QLabel, QLineEdit, QDialogButtonBox, QPushButton, QApplication, QGraphicsPixmapItem, QInputDialog
from aritmatika import Aritmatika

class Ui_MainWindow_aritmatika(object):

    def __init__(self):
        self.imagePath = None
        self.imagePath2 = None
        self.imagefile = None
        self.imagefile2 = None
        self.imageResult = None

    def saveAs(self):
        if hasattr(self, 'imageResult') and self.imageResult is not None:
            # Buka dialog untuk memilih lokasi dan memberi nama file
            options = QFileDialog.Options()
            fileName, _ = QFileDialog.getSaveFileName(None, "Save Image As", "", "PNG Files (*.png);;JPEG Files (*.jpg);;BMP Files (*.bmp)", options=options)
            
            if fileName:
                # Simpan gambar ke lokasi yang dipilih dengan nama file baru
                self.imageResult.save(fileName)
                print(f"Gambar disimpan di: {fileName}")
            else:
                print("Penyimpanan dibatalkan.")
        else:
            print("Tidak ada gambar untuk disimpan.")

    def openImage1(self):
        # Show file dialog to select an image file
        options = QFileDialog.Options()
        fileName, _ = QFileDialog.getOpenFileName(None, "Open Image", "", "Image Files (*.png *.jpg *.bmp *.jpeg)", options=options)
        
        if fileName:
            self.imagePath = fileName
            image_path = fileName
            img = Image.open(image_path)
            self.imagefile = img
            # img.show()

            # Load the image and display it in the QGraphicsView
            self.image_pixmap = QtGui.QPixmap(fileName)

            # Get the size of the QGraphicsView
            view_width = self.graphicsView.width()
            view_height = self.graphicsView.height()

            # Scale the pixmap to fit the QGraphicsView, preserving the aspect ratio
            scaled_pixmap = self.image_pixmap.scaled(view_width, view_height, QtCore.Qt.KeepAspectRatio)

            self.scene.clear()  # Clear any previous content in the scene
            self.scene.addPixmap(scaled_pixmap)
            # self.graphicsView.fitInView(self.scene.itemsBoundingRect(), QtCore.Qt.KeepAspectRatio)
            self.graphicsView.setSceneRect(self.scene.itemsBoundingRect())

    def openImage2(self):
        # Show file dialog to select an image file
        options = QFileDialog.Options()
        fileName, _ = QFileDialog.getOpenFileName(None, "Open Image", "", "Image Files (*.png *.jpg *.bmp *.jpeg)", options=options)
        
        if fileName:
            self.imagePath2 = fileName
            image_path = fileName
            img = Image.open(image_path)
            self.imagefile2 = img
            # img.show()

            # Load the image and display it in the QGraphicsView
            self.image_pixmap = QtGui.QPixmap(fileName)

            # Get the size of the QGraphicsView
            view_width = self.graphicsView_2.width()
            view_height = self.graphicsView_2.height()

            # Scale the pixmap to fit the QGraphicsView, preserving the aspect ratio
            scaled_pixmap = self.image_pixmap.scaled(view_width, view_height, QtCore.Qt.KeepAspectRatio)

            self.scene2.clear()  # Clear any previous content in the scene
            self.scene2.addPixmap(scaled_pixmap)
            # self.graphicsView.fitInView(self.scene.itemsBoundingRect(), QtCore.Qt.KeepAspectRatio)
            self.graphicsView_2.setSceneRect(self.scene2.itemsBoundingRect())
    
    def addition(self):
        obj = Aritmatika(self.imagePath, self.imagePath2)

        result = obj.penjumlahan()

        self.showImageResult(result)

    def substraction(self):
        obj = Aritmatika(self.imagePath, self.imagePath2)
        
        result = obj.pengurangan()

        self.showImageResult(result)

    def multiplication(self):
        obj = Aritmatika(self.imagePath, self.imagePath2)
        
        result = obj.perkalian()

        self.showImageResult(result)

    def distribution(self):
        obj = Aritmatika(self.imagePath, self.imagePath2)
        
        result = obj.pembagian()

        self.showImageResult(result)

    def or_(self):
        obj = Aritmatika(self.imagePath, self.imagePath2)
        
        result = obj.or_operation()

        self.showImageResult(result)

    def and_(self):
        obj = Aritmatika(self.imagePath, self.imagePath2)
        
        result = obj.and_operation()

        self.showImageResult(result)

    def xor_(self):
        obj = Aritmatika(self.imagePath, self.imagePath2)
        
        result = obj.xor_operation()

        self.showImageResult(result)

    def showImageResult(self, output):
        self.imageResult = output

        # Save the image to a temporary file
        with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as temp_file:
            temp_file_path = temp_file.name
            output.save(temp_file_path)

        # Load the image from the temporary file into QPixmap
        img_pixmap = QtGui.QPixmap(temp_file_path)

        # Get the size of the QGraphicsView
        view_width = self.graphicsView_3.width()
        view_height = self.graphicsView_3.height()

        # Scale the pixmap to fit the QGraphicsView, preserving the aspect ratio
        scaled_pixmap = img_pixmap.scaled(view_width, view_height, QtCore.Qt.KeepAspectRatio)

        self.sceneOutput.clear()  # Clear any previous content in the scene
        self.sceneOutput.addPixmap(scaled_pixmap)
        # self.graphicsView.fitInView(self.scene.itemsBoundingRect(), QtCore.Qt.KeepAspectRatio)
        self.graphicsView_3.setSceneRect(self.sceneOutput.itemsBoundingRect())
        
        # delete temp file
        os.remove(temp_file_path)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1001, 396)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 30, 321, 281))
        self.graphicsView.setObjectName("graphicsView")
        # Initialize a scene for the GraphicsView
        self.scene = QGraphicsScene()
        self.graphicsView.setScene(self.scene)
        
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_2.setGeometry(QtCore.QRect(340, 30, 321, 281))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.scene2 = QGraphicsScene()
        self.graphicsView_2.setScene(self.scene2)

        self.graphicsView_3 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_3.setGeometry(QtCore.QRect(670, 30, 321, 281))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.sceneOutput = QGraphicsScene()
        self.graphicsView_3.setScene(self.sceneOutput)

        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 320, 981, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(350, 10, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(680, 10, 47, 13))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1001, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuArithmatical_Operation = QtWidgets.QMenu(self.menubar)
        self.menuArithmatical_Operation.setObjectName("menuArithmatical_Operation")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # open image 1
        self.actionOpen_Image_1 = QtWidgets.QAction(MainWindow)
        self.actionOpen_Image_1.setObjectName("actionOpen_Image_1")
        self.actionOpen_Image_1.triggered.connect(self.openImage1)
        
        # open image 2
        self.actionOpen_Image_2 = QtWidgets.QAction(MainWindow)
        self.actionOpen_Image_2.setObjectName("actionOpen_Image_2")
        self.actionOpen_Image_2.triggered.connect(self.openImage2)
        
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionSave_as.triggered.connect(self.saveAs)

        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")

        self.actionPenjumlahan = QtWidgets.QAction(MainWindow)
        self.actionPenjumlahan.setObjectName("actionPenjumlahan")
        self.actionPenjumlahan.triggered.connect(self.addition)
        
        self.actionPengurangan = QtWidgets.QAction(MainWindow)
        self.actionPengurangan.setObjectName("actionPengurangan")
        self.actionPengurangan.triggered.connect(self.substraction)

        self.actionPerkalian = QtWidgets.QAction(MainWindow)
        self.actionPerkalian.setObjectName("actionPerkalian")
        self.actionPerkalian.triggered.connect(self.multiplication)

        self.actionPembagian = QtWidgets.QAction(MainWindow)
        self.actionPembagian.setObjectName("actionPembagian")
        self.actionPembagian.triggered.connect(self.distribution)

        self.actionAND = QtWidgets.QAction(MainWindow)
        self.actionAND.setObjectName("actionAND")
        self.actionAND.triggered.connect(self.and_)

        self.actionOR = QtWidgets.QAction(MainWindow)
        self.actionOR.setObjectName("actionOR")
        self.actionOR.triggered.connect(self.or_)

        self.actionXOR = QtWidgets.QAction(MainWindow)
        self.actionXOR.setObjectName("actionXOR")
        self.actionXOR.triggered.connect(self.xor_)

        self.actionXANF = QtWidgets.QAction(MainWindow)
        self.actionXANF.setObjectName("actionXANF")
        self.menuFile.addAction(self.actionOpen_Image_1)
        self.menuFile.addAction(self.actionOpen_Image_2)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClear)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuArithmatical_Operation.addAction(self.actionPenjumlahan)
        self.menuArithmatical_Operation.addAction(self.actionPengurangan)
        self.menuArithmatical_Operation.addAction(self.actionPerkalian)
        self.menuArithmatical_Operation.addAction(self.actionPembagian)
        self.menuArithmatical_Operation.addAction(self.actionAND)
        self.menuArithmatical_Operation.addAction(self.actionOR)
        self.menuArithmatical_Operation.addAction(self.actionXOR)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuArithmatical_Operation.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Input 1"))
        self.label_2.setText(_translate("MainWindow", "Input 2"))
        self.label_3.setText(_translate("MainWindow", "Output"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuArithmatical_Operation.setTitle(_translate("MainWindow", "Arithmatical Operation"))
        self.actionOpen_Image_1.setText(_translate("MainWindow", "Open Image 1"))
        self.actionOpen_Image_2.setText(_translate("MainWindow", "Open Image 2"))
        self.actionSave_as.setText(_translate("MainWindow", "Save As.."))
        self.actionClear.setText(_translate("MainWindow", "Clear"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionPenjumlahan.setText(_translate("MainWindow", "Penjumlahan"))
        self.actionPengurangan.setText(_translate("MainWindow", "Pengurangan"))
        self.actionPerkalian.setText(_translate("MainWindow", "Perkalian"))
        self.actionPembagian.setText(_translate("MainWindow", "Pembagian"))
        self.actionAND.setText(_translate("MainWindow", "AND"))
        self.actionOR.setText(_translate("MainWindow", "OR"))
        self.actionXOR.setText(_translate("MainWindow", "XOR"))
        self.actionXANF.setText(_translate("MainWindow", "XAND"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_aritmatika()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
